### ISSUE TITLE
Windows VM

### ISSUE THREAD

**Issue by mgax** [vmck/vmck#12]
SO has homework for Linux and Windows. We need to run the Windows checker.

**Comment by mgax** [comment]
I was able to start the [SO Windows VM](https://ocw.cs.pub.ro/courses/so/info/mv#windows) by converting the disk (`qemu-img convert so-vm-win7/so-vm-win7.vmdk disk.qcow -O qcow2`) then running:

```shell
/usr/bin/qemu-system-x86_64                               \
  -name disk.qcow                                         \
  -machine type=pc,accel=kvm                              \
  -cpu host                                               \
  -enable-kvm                                             \
  -smp 2                                                  \
  -m 1024M                                                \
  -vnc :14                                                \
  -drive file=./disk.qcow                                 \
  -netdev user,id=user.0,hostfwd=hostfwd=tcp::21350-:22   \
  -device virtio-net,netdev=user.0                        \
  -usbdevice tablet
```

The image contains "FreeSSHd" (it's probably already running, but I reinstalled it by mistake) and `nc localhost 22` prints the welcome message `SSH-2.0-WeOnlyDo 2.1.3`, so the sshd must be up, but I couldn't connect to it from the host machine on the port `21350` that's forwarded.

For reference:
```
$ qemu-system-x86_64 --version
QEMU emulator version 2.8.1(Debian 1:2.8+dfsg-6+deb9u8)
Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers
```

**Comment by mgax** [comment]
For SSH to work, the machine needs a working network interface, so I manually installed virtio network drivers from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso (add `-drive file=virtio-win.iso,media=cdrom` to qemu command).

FreeSSHd needs manual configuration for users, keys etc; it looks like OpenSSH is the better option for the server.

Here's how other people use Windows guests in Vagrant:
* https://dev.to/jeikabu/reusable-windows-vms-with-vagrant-2h5c
* https://www.vagrantup.com/docs/boxes/base.html#windows-boxes

It also looks like SSH will log into powershell, so we need to run some commands differently, and maybe the Vagrantfile will have to be [windows-specific](https://dev.to/jeikabu/reusable-windows-vms-with-vagrant-2h5c#vagrantfile):

```
Vagrant.configure("2") do |config|
    config.vm.box = "win10_ltsc_2019"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    # 3389 RDP
    config.vm.network "forwarded_port", guest: 3389, host: 3389
end
```

**Comment by gmuraru** [comment]
Won't fix! If we ever want a windows machine for testing we will see then.
