### ISSUE TITLE
Create a single Allocation

### ISSUE THREAD

**Issue by mgax** [vmck/vmck#25]
For jobs that fail, Nomad creates a 2nd allocation, hoping that it will work, after the first one failed. We should disable this behaviour, at least for now.

**Comment by tudalex** [comment]
@mgax This seems fixed. It is not creating a new allocation for me.

**Comment by mgax** [comment]
> This seems fixed. It is not creating a new allocation for me.

@tudalex It only happens on certain kinds of errors, which I can't remember now. I will update the issue with more info when it happens again.
