### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by mgax** [vmck/vmck#27]
Run the test suite in Travis CI. This requires spinning up a Nomad cluster in the Travis VM, and perhaps mocking out the qemu-kvm job with a docker replacement, because Travis probably won't give us KVM.

Here's how to [run Kube in Travis](https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube); running Nomad should be similar.

**Comment by mgax** [comment]
This project looks like it's running TravisCI tests and spinning up a Nomad cluster inside the test VM: https://github.com/jrxFive/python-nomad/blob/master/.travis.yml

**Comment by gabriel-v** [comment]
We have a CI running at https://jenkins.liquiddemo.org/vmck/vmck/.

Let's run `pytest` as another step after flake8, [here](https://github.com/vmck/vmck/blob/209b00c80a7f997bcc780530a9f947db92337572/.drone.yml#L10). This step would start some `python:3.7` image, install pipenv, use it to install the project dependencies (check the Dockerfile), and finally run `pytest`.

**Comment by mgax** [comment]
Done, a long time ago :)
