### ISSUE TITLE
Log errors to Sentry

### ISSUE THREAD

**Issue by mgax** [vmck/vmck#4]
We can use the free version: https://sentry.io/signup/

**Comment by dixi3** [comment]
Hi can I work on this?

**Comment by mgax** [comment]
> Hi can I work on this?

Sure, no need to ask for permission.

**Comment by dixi3** [comment]
I think i set it up. Can i transfer the sentry project over to you?

**Comment by mgax** [comment]
> I think i set it up. Can i transfer the sentry project over to you?

Just add me to the project for now please.

**Comment by dixi3** [comment]
Ok i've sent you an invite.

**Comment by mgax** [comment]
Thanks, accepted. That there is a beautiful stack trace!

So now you're making a pull request, right? :)
