### ISSUE TITLE
Make vmck.nomad configurable

### ISSUE THREAD

**Issue by Jokeswar** [vmck/vmck#67]
The following values in exampls/vmck.nomad are currently hardcoded:

- [x] imghost/nginx/config/volumes: host volume for vmck-images
- ~imghost/nginx/service/check: interval and timeout~
- [x] vmck/vmck/config/volumes: host volume vmck/data
- [x] vmck/vmck/template: CONSUL_URL and NOMAD_URL
- ~vmck/vmck/service/check: interval and timeout~

They are referenced in the following PR #66. An example can be found [here](https://github.com/liquidinvestigations/node/blob/master/templates/drone.nomad).

**Comment by mgax** [comment]
We can live with checks being hardcoded.
